version: 1

generalize_profiles_path: "./generalize-profiles.yaml"

grid:
  cell_size: 0.225    # identique au scope departement
  overlap: 0.005

inputs:
  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/PARCELLE_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/BATIMENT_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/TSURF_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/SECTION_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/TRONFLUV_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/TRONROUTE_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/LIEUDIT_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/ZONCOMMUNI_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/TLINE_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/TPOINT_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

  - path: "${CADASTRE_DATA_ROOT}/{${ZONES}}/gpkg/NUMVOIE_id.gpkg"
    source_srs: "EPSG:2154"
    target_srs: "EPSG:4326"

output:
  directory: "${OUTPUT_DIR}/mp/"
  filename_pattern: "CADASTRE-{col:03}-{row:03}.mp"
  overwrite: true
  base_id: ${BASE_ID}

header:
  name: "CADASTRE-{col:03}-{row:03}"
  copyright: "2026 Allfab Studio - DGFiP Plan Cadastral Informatisé 2026"
  levels: "4"
  level0: "24"
  level1: "21"
  level2: "18"
  level3: "16"
  simplify_level: "0"
  tree_size: "1000"
  rgn_limit: "1024"
  transparent: "Y"
  marine: "N"
  preprocess: "F"
  lbl_coding: "9"
  routing: "N"

rules: ./garmin-rules.yaml

error_handling: "continue"
