[IMG ID]
Name=Edge Features Ordered
ID=51245182
CodePage=1252
Datum=WGS 84
[END-IMG ID]

[POI]
Type=0x0100
Label=Ordered 1
Data0=(2.0,48.0)
[END]

[POI]
Type=0x0100
Label=Ordered 2
Data0=(2.02,48.05)
[END]

[POI]
Type=0x0100
Label=Ordered 3
Data0=(2.04,48.1)
[END]

[POI]
Type=0x0100
Label=Ordered 4
Data0=(2.06,48.15)
[END]

[POI]
Type=0x0100
Label=Ordered 5
Data0=(2.08,48.2)
[END]

[POI]
Type=0x0100
Label=Ordered 6
Data0=(2.1,48.25)
[END]

[POI]
Type=0x0100
Label=Ordered 7
Data0=(2.12,48.3)
[END]

[POI]
Type=0x0100
Label=Ordered 8
Data0=(2.14,48.35)
[END]

[POI]
Type=0x0100
Label=Ordered 9
Data0=(2.16,48.4)
[END]

[POI]
Type=0x0100
Label=Ordered 10
Data0=(2.18,48.45)
[END]

[POI]
Type=0x0100
Label=Ordered 11
Data0=(2.2,48.5)
[END]

[POI]
Type=0x0100
Label=Ordered 12
Data0=(2.22,48.55)
[END]

[POI]
Type=0x0100
Label=Ordered 13
Data0=(2.24,48.6)
[END]

[POI]
Type=0x0100
Label=Ordered 14
Data0=(2.26,48.65)
[END]

[POI]
Type=0x0100
Label=Ordered 15
Data0=(2.2800000000000002,48.7)
[END]

[POI]
Type=0x0100
Label=Ordered 16
Data0=(2.3,48.75)
[END]

[POI]
Type=0x0100
Label=Ordered 17
Data0=(2.32,48.8)
[END]

[POI]
Type=0x0100
Label=Ordered 18
Data0=(2.34,48.85)
[END]

[POI]
Type=0x0100
Label=Ordered 19
Data0=(2.36,48.9)
[END]

[POI]
Type=0x0100
Label=Ordered 20
Data0=(2.38,48.95)
[END]
