server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy Umami tracker pour éviter le blocage par les ad blockers
    location /js/ {
        proxy_pass https://umami.allfabox.fr/;
        proxy_set_header Host umami.allfabox.fr;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
