http:
  routers:
    pages-server:
      rule: "Host(`maps.garmin.allfabox.fr`)"
      entryPoints:
        - websecure
      service: pages-server
      tls:
        certResolver: letsencrypt

  services:
    pages-server:
      loadBalancer:
        servers:
          - url: "http://pages-server:8080"
